### ISSUE TITLE
More Detailed Instructions Needed

### ISSUE THREAD

**Issue by CynthiaBlue** [alexandesigner/quasar-meteor#10]
Are there more detailed instructions somewhere in order to learn how to use this project?
When I try the basic commands in the instructions I only get errors.

Please include more information for those of us brand new to meteor and npm (and Quasar).

**Comment by alexandesigner** [comment]
@CynthiaBlue Thanks for the feedback, sorry for the delay in replying.. 

I updated the Quasar version to v2 and also made some updates to the readme, just follow the steps.. 

If you still have any difficulties please let me know that I will help you!

### Install dependencies
```
npm install
```

### Install meteor client bundler
```
npm run generate:bundler
```

### This will generate a ``meteor.bundle.js`` file in ``/node_modules``, make sure it really exists before running the application.

### Run application at localhost:4000
```
npm run api
```

### Serve with hot reload at localhost:3000
```
npm run dev
```

### Build for production with minification
```
npm run build
```

### Lint code
```
npm run lint
```
